RUN FROM ROOT OF REPOSITORY

In [1]:
import numpy as np
import torch

from torch_geometric.loader import DataLoader, ImbalancedSampler

from src.features.dataset import DepressionDataset

In [2]:
batch_size = 64

train_set = DepressionDataset('train', 'bert', 'dependency')
sampler = ImbalancedSampler(train_set)
train_loader = DataLoader(train_set, batch_size=batch_size, sampler=sampler)

In [3]:
from tqdm import tqdm

a = []

for batch in tqdm(train_loader):
    b = batch.y.cpu().numpy()
    b = np.bincount(b)
    b = b[None, :]
    a.append(b)

a = np.concatenate(a, axis=0)

a.mean(axis=0), a.std(axis=0)

100%|██████████| 139/139 [02:10<00:00,  1.07it/s]


(array([21.28776978, 21.35251799, 21.32374101]),
 array([3.89104229, 3.58827689, 3.86501711]))

No sampler:

```
(array([14.17985612, 43.30215827,  6.48201439]),
 array([3.36561495, 3.6750269 , 2.34858757]))
```

With sampler: (my implementation)

```
(array([14.3381295 , 42.5971223 ,  7.02877698]),
 array([3.31457205, 3.75072065, 2.4493207 ]))
```

With sampler: (torch geo implementation)

```
(array([21.28776978, 21.35251799, 21.32374101]),  # works
 array([3.89104229, 3.58827689, 3.86501711]))
```